project_id = "jytbfknhebutyshjzdxt"

[functions.process-bulk-images]
verify_jwt = false

[functions.match-images-cron]
verify_jwt = false

[functions.generate-seo-content]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.list-payment-methods]
verify_jwt = false

[functions.delete-payment-method]
verify_jwt = false

[functions.capture-payment]
verify_jwt = false

[functions.set-save-card]
verify_jwt = false
